#!/bin/bash

if [ "$#" == 1 ]
then 
	KOD="$1"
	YESTERDAY=$(date -d yesterday +%s)
	TODAY=$(echo "$YESTERDAY"+24*60*60|bc)
	curl -s 'https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=csv&stationString='"$KOD"'&startTime='"$YESTERDAY"'&endTime='"$TODAY"''| sed 's/.*elevation_m//'


elif [ "$#" == 2 ]
then
START=$(echo $1 | date -d $1 +%s)

KONIEC=$(echo "$START"+24*60*60|bc)

KOD="$2"


curl -s 'https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=csv&stationString='"$KOD"'&startTime='"$START"'&endTime='"$KONIEC"''| sed 's/.*elevation_m//'	


else
	echo "zadaj 2 argumenty: datum vo formate DD/MM/YYYY a stvorpisomenovy kod letiska"
	exit 1
fi 









